name: Deploy Documentation
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup pandoc
        uses: nikeee/setup-pandoc@v1
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=18'
      - name: Setup Hexo and dependencies and Deploy
        run: |
          npm install hexo-cli -g
          npm install
          hexo d
